# Generated by Django 4.2.20 on 2025-06-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IonAPICredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ti', models.CharField(max_length=100)),
                ('cn', models.CharField(max_length=50)),
                ('dt', models.CharField(max_length=10)),
                ('ci', models.TextField()),
                ('cs', models.TextField()),
                ('iu', models.URLField()),
                ('pu', models.URLField()),
                ('oa', models.CharField(max_length=100)),
                ('ot', models.CharField(max_length=100)),
                ('or_field', models.CharField(db_column='or', max_length=100)),
                ('sc', models.JSONField(default=list)),
                ('ev', models.CharField(max_length=50)),
                ('v', models.CharField(max_length=10)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
