# Generated by Django 4.2.20 on 2025-11-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_remove_activeoperation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeoperation',
            name='company_id',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activeoperation',
            name='operated_item',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activeoperation',
            name='operation',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activeoperation',
            name='operation_status',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activeoperation',
            name='order',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activeoperation',
            name='planned_start_date',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activeoperation',
            name='reference_operation_machine_type',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activeoperation',
            name='reference_operation_work_center',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activeoperation',
            name='routing_quantity',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='activeoperation',
            name='username',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
